import {
    AlertTriangle,
    CloudRain,
    Wind,
    Thermometer,
    TrendingUp,
    TrendingDown,
    Activity,
    Smile,
    Sun,
    CheckCircle,
    Heart,
    FileText,
    Calendar,
    BarChart3,
    Info,
    Droplets,
    Eye,
    Umbrella,
    Snowflake,
    Zap,
} from 'lucide-react';

export const insightIconMap = {
    'alert-triangle': AlertTriangle,
    'cloud-rain': CloudRain,
    wind: Wind,
    thermometer: Thermometer,
    'trending-up': TrendingUp,
    'trending-down': TrendingDown,
    activity: Activity,
    smile: Smile,
    sun: Sun,
    'circle-check': CheckCircle,
    heart: Heart,
    'file-text': FileText,
    calendar: Calendar,
    'chart-bar': BarChart3,
    info: Info,
    droplets: Droplets,
    eye: Eye,
    umbrella: Umbrella,
    snowflake: Snowflake,
    zap: Zap,
} as const;

export type InsightIconName = keyof typeof insightIconMap;
